#!/usr/bin/env python

import sys, os

def show_help(callname):
	print callname + ' (nodenum)'

if __name__ == '__main__':
	if len(sys.argv) != 2:
		show_help(sys.argv[0])
		sys.exit(-1)

	try:
		arg1 = sys.argv[1]
		nodenum = int(arg1)
	except ValueError:
		show_help(sys.argv[0])
		sys.exit(-1)

	os.execlp('/bin/ssh', '/bin/ssh', 'node%d' % nodenum)
