#!/usr/bin/env python3

import sys
import argparse
import requests
from urllib import parse

def parse_args():
	parser = argparse.ArgumentParser()
	parser.add_argument('msg', help='The message to send')
	return parser.parse_args().msg

def main():
	msg = parse_args()
	quoted_msg = parse.quote(msg)
	requests.get('http://119.29.60.132/cgi-bin/dashboard/dash.cgi?mode=put&msg=%s' % quoted_msg)

if __name__ == '__main__':
	sys.exit(main())
