#!/usr/bin/env python3

TITLE_DEFAULT = 'Node19'

import sys
import argparse
import requests
from urllib import parse

def parse_args():
	parser = argparse.ArgumentParser()
	parser.add_argument('msg', help='The message to send')
	parser.add_argument('-t', '--title', help='Use an alternative title name instead of %s' % TITLE_DEFAULT)
	return parser.parse_args()

def main():
	args = parse_args()
	quoted_msg = parse.quote(args.msg)
	title = args.title and args.title or TITLE_DEFAULT
	quoted_title = parse.quote(title)
	#requests.get('http://119.29.60.132/cgi-bin/dashboard/dash.cgi?mode=put&msg=%s' % quoted_msg)
	requests.get('http://222.195.68.242:30080/cgi-bin/notify/n.cgi?t=%s&b=%s' % (quoted_title, quoted_msg))

if __name__ == '__main__':
	sys.exit(main())
