#!/bin/bash

#CLUSTER_SIZE=5
CLUSTER_SIZE=19

if [ "$1" == "-h" ]; then
  >&2 echo "Usage: $0 [-y] [-p TARGET_PATH] [-b] [FILES]"
  >&2 echo
  >&2 echo "Warning: optional arguments MUST be arranged IN ORDER as above"
  >&2 echo "Optional arguments:"
  >&2 echo "           -p TARGET_PATH        Set target path. If not, you'll be prompted to give one."
  >&2 echo "           -b                    Broadcast mode: send files to all other machines."
  >&2 echo "           FILES                 Target files. If not set, you'll be prompted to provide."
  exit 0
fi

SKIP_CHECK=
if [ "$1" == "-y" ]; then
  shift
  SKIP_CHECK=true
fi

if [ "$1" == "-p" ]; then
  shift
  TARGET_PATH="$1"
  shift
fi

NODE_LIST=
if [ "$1" == "-b" ]; then
  shift
  # Set targets from my hostname
  echo -e "\e[1;35mWarning: broadcast flag set.\e[0m"
  my_hostname=$(hostname)
  echo "Get my hostname: ${my_hostname}"
  my_nodeid=${my_hostname#node*}
  echo "Get my nodeid: ${my_nodeid}"

  for ((i=1; i<=${CLUSTER_SIZE}; i++)); do
	if test $my_nodeid -ne $i; then
	  NODE_LIST="${NODE_LIST} $i"
	fi
  done
else
  echo "Select nodes: (1-${CLUSTER_SIZE})"
  read NODES_SYMBOLS

  NODES=
  LAST_NODE=
  RANGE_FLAG=false
  for sym in $NODES_SYMBOLS ; do
  	if [ $sym == "-" ] && [ "$LAST_NODE" ]; then
  		if [ $RANGE_FLAG == "true" ]; then
  			echo "Bad input: two symbols '-' together"
  			exit
  		else
  			RANGE_FLAG=true
  		fi
  	elif [ $sym -ge 1 ] && [ $sym -le ${CLUSTER_SIZE} ]; then
  		if [ $RANGE_FLAG == "true" ]; then
  			NODES="$NODES `seq $LAST_NODE $sym`"
  			LAST_NODE=
  			RANGE_FLAG=false
  		else
  			NODES="$NODES $LAST_NODE"
  			LAST_NODE=$sym
  		fi
  	else
  		echo "Bad input: $sym"
  		exit
  	fi
  done
  if [ $RANGE_FLAG == "true" ]; then
  	echo "Bad input: no end!"
  	exit
  elif [ "$LAST_NODE" ]; then
  	NODES="$NODES $LAST_NODE"
  fi
  
  for node in $NODES ; do
  	NODE_LIST="$NODE_LIST $node"
  done
fi

if [ $# -lt 1 ]; then
	FILES=
else
	FILES="$*"
fi

#######################################################################
if [ ! "$FILES" ]; then
	echo "Files:"
	read -e FILES
fi

if [ ! "${TARGET_PATH}" ]; then
  echo "Target path: (optional, main directory by default)"
  wd=$(pwd)
  cd ~
  read -e TARGET_PATH
  cd $wd
fi

if [ ! "${TARGET_PATH}" ]; then
	TARGET_PATH=.
fi

#######################################################################
if [ -z "${SKIP_CHECK}" ]; then
  echo -e "Copying file(s): \n\e[1;33m${FILES}\e[0m\nto these nodes:\n\e[1;33m$NODE_LIST\e[0m,\nwithin this directory:\n\e[1;33m${TARGET_PATH}\e[0m"
  echo "Press [Enter] to continue or [Ctrl-C] to exit"
  read
  echo
fi

for node in $NODE_LIST; do
	echo -e "\e[1;33mscp ${FILES} node$node:${TARGET_PATH}\e[0m"
	scp -q ${FILES} node$node:${TARGET_PATH} &
done
wait
